# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      # - db
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: HIS_hosp
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=HIS_hosp,test_his_hosp  # ระบุ databases ทั้งสอง
      - POSTGRES_MULTIPLE_USERS=postgres,postgres  # ระบุ users ทั้งสอง
      - POSTGRES_MULTIPLE_PASSWORDS=postgres,postgres  # ระบุ passwords ทั้งสอง

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    command: >
      bash -c "
      chmod a+x /docker-entrypoint-initdb.d/init-multiple-dbs.sh &&
      exec docker-entrypoint.sh postgres
      "
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app



volumes:
  postgres_data:
  test_postgres_data:
